### PR TITLE
Django 1.10

### PR DESCRIPTION
**Pull request by mattbriancon**

### CODE REVIEW

**Comment by jschneier** [comment]
@czpython @vxsx what can I do to get this merged? This is the only thing gating my Django 1.10 upgrade path and I have tested this branch on a fork and everything seems to be working.

**Comment by mattbriancon** [comment]
I'll try to get some more of the tests passing tonight or tomorrow morning.

**Comment by czpython** [comment]
Thanks for checking with us @jschneier. I totally missed this.
Let us know if you'd like some assistance on this @mattbriancon.

**Comment by mattbriancon** [comment]
Closing in favor of https://github.com/divio/django-filer/pull/918

**Pull request closed without merging**
