### PR TITLE
Remove all uses of `patterns`

### LINKED ISSUE #717: deprecation for the url patterns
/media/sunder/Work/ReviewOrb/lib/python3.4/site-packages/filer/admin/folderadmin.py:224: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='filer-directory_listing-unfiled_images'),

/media/sunder/Work/ReviewOrb/lib/python3.4/site-packages/filer/admin/clipboardadmin.py:58: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='filer-ajax_upload'),

### PR DESCRIPTION
**Pull request by mattbriancon**
Fixes #717

### CODE REVIEW

**Comment by stefanfoulis** [comment]
thanks @mattbriancon !
Do we need any special handling to keep supporting Django 1.6? I can't recall if 1.6 already supports patterns as a list.

**Comment by stefanfoulis** [comment]
oh, and the tests went bonkers

**Comment by mattbriancon** [comment]
I'll look into the tests the weekend. Not sure what happened there :confused:.

**Comment by mattbriancon** [comment]
Regarding Django 1.6, I figured my approach was fine because [filer/urls.py](https://github.com/divio/django-filer/blob/develop/filer/urls.py) had already been converted to use a list. Happy to add a compatibility layer if necessary.

**Comment by Wegi** [comment]
Hey what is the status on this patch? Is any help needed? Would love a filer version where the Warnings disapear. ;)

**Comment by mattbriancon** [comment]
Apologies! I'll try to get this up to date with the tests passing by this weekend.

**Comment by mattbriancon** [comment]
@stefanfoulis @Wegi should be good to go!

**Comment by czpython** [comment]
@mattbriancon Thanks!

**Pull request merged**
