### PR TITLE
feature: adds edit btn to image widget

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

- adds edit button to filer image widget 

screen shot 2016-11-25 at 09 46 12

screen shot 2016-11-25 at 09 46 31

### CODE REVIEW

**Comment by FinalAngel** [comment]
@lory87 please also provide a screenshot, eventually big and when its small (narrow)

**Comment by lory87** [comment]
@FinalAngel screenshots are added

**Comment by FinalAngel** [comment]
@lory87 the pencil icon is not really vertically centered

**Comment by lory87** [comment]
@FinalAngel 

screen shot 2016-11-25 at 09 59 15

**Pull request merged**
