### PR TITLE
drag and drop widget upload styles

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

- adds icons gulp task. Please ignore iconography.sass and iconfont.sass files

|UPLOAD|DRAG AND DROP|UPLOADED|
|---|---|---|
|screen shot 2015-12-08 at 16 03 55|screen shot 2015-12-08 at 16 04 59 2|screen shot 2015-12-08 at 17 09 45|

### CODE REVIEW

**Comment by Flight** [comment]
Font-awesome is already connected here

**Comment by lory87** [comment]
@Flight but I can't update html have to use an include.

**Comment by Flight** [comment]
LGTM

**Comment by FinalAngel** [comment]
LGTM

**Pull request merged**
