### PR TITLE
Adding support for Django 2.0/2.1

### PR DESCRIPTION
**Pull request by vThaian**
Based on #1086 and #1030 

Fixes:
* Fixed history link for folder and image object
* Fixed rendering canonical URL in change form

### CODE REVIEW

**Comment by wooyek** [comment]
Will it be merged anytime soon or will it suffer the same fate as #1086 and #1030 ;P

**Comment by wooyek** [comment]
But still not merged :(

**Comment by wooyek** [comment]
Build failed… [Aaaaand it's gone.](https://youtu.be/TGwZVGKG30s?t=14) ;)

**Comment by mattbriancon** [comment]
Any thoughts @yakky? This is the only blocker for us upgrading to Django 2.0 for one of our projects.

**Comment by vchacko** [comment]
Waiting for this to be merged

**Comment by vchacko** [comment]
Sincewe were in emergency and couldnt wait, I created a fork with this changes. 
`pip install git+https://github.com/atemon/django-filer.git`
We havent finished testing with new module yet

**Comment by yihuang** [comment]
We also used a [forked version](https://github.com/yihuang/django-filer/tree/add-support-for-django20-21) for Django 2.1, and makes some other enhancements based on that.

**Comment by peterfarrell** [comment]
@vThaian Thank you!

**Pull request merged**
