### PR TITLE
Add link to `canonical_url` in column actions for files

### PR DESCRIPTION
**Pull request by 1vank1n**
Hi! It's tiny enhachment for usability.

### CODE REVIEW

**Comment by FinalAngel** [comment]
@1vank1n would you provide a quick screenshot on what you want to achieve?

**Comment by mkoistinen** [comment]
@1vank1n and/or @lory87 can you prepare this for merging?

**Comment by 1vank1n** [comment]
@FinalAngel of course:

screen shot 2016-06-22 at 10 44 54

Advantage: get canonical url at file listing.

**Comment by FinalAngel** [comment]
LGTM @mkoistinen

**Comment by yakky** [comment]
@1vank1n would you rebase this on current develop to fix conflicts?

**Comment by 1vank1n** [comment]
@yakky no problem! Done!

**Comment by yakky** [comment]
@1vank1n thanks. There are still conflict markers in the patch. Could you check those?

**Comment by 1vank1n** [comment]
@yakky hmm... i have not see conflict... "All checks have passed". Where's to find conflict?

**Comment by yakky** [comment]
@1vank1n have a look at the diff here on github. There are conflicts on ``directory_table.html`` and ``_navigator.scss``

**Comment by 1vank1n** [comment]
@yakky fixed. Now (in new version) there is icon `download`. Maybe in new version of django-filer my icon `canonical url` are unnecessary.

**Comment by yakky** [comment]
@1vank1n thanks!

**Pull request merged**
