### PR TITLE
Fix a couple of bugs with the admin styling

### PR DESCRIPTION
**Pull request by tdsymonds**
These changes will resolve:

1. On smaller screen widths the formatting for the inline image icon/preview was not vertically centered in the container.
2. On smaller screen widths the height for the container of the "choose file" button was not increasing as the "drop your file" text dropped to a second row. 
3. When not using "djangocms-admin-style" the search input in the admin section overlays the search icon.

### CODE REVIEW

**Comment by tdsymonds** [comment]
Issues 1 and 2 before can be seen here before:

before

And after:

after

Issue 3 before:

before 2

After:

after 2

I'm not sure why the Travis build is failing as this shouldn't effect it. Looks like it's a common issue accross the pull requests though.

**Comment by benzkji** [comment]
looking goooood.

**Comment by yakky** [comment]
@tdsymonds couldyou amend the PR as per vxsx comment?

**Comment by yakky** [comment]
@tdsymonds I'd really like this into next patch version, but the change requested by Vadim is essential to be able to merge this. At this stage, it's not even clear the code changes you made and we cannot port this for you

**Comment by tdsymonds** [comment]
@vxsx @yakky guys, sorry for the delay. Look, I didn't realise there were sass files when I made the changes, so applied directly to the CSS. I made these changes such a long time ago, that I'm not 100% what the changes were. Apologies! Will try and revisit if I get some time in the coming weeks.

**Comment by yakky** [comment]
@tdsymonds thanks and sorry it took some time to get back to you

**Comment by tdsymonds** [comment]
No worries @yakky, I should have checked more carefully, so it's my own fault. Like I said, if I get some time I will try and revisit. Just fairly busy at the moment, so no guarantee when that will be!

**Comment by yakky** [comment]
@tdsymonds thanks. If it will not fit into 1.2.6 (still no ETA, anyway) we'll merge in future releases when ready

**Comment by vxsx** [comment]
@tdsymonds i believe this one covers it https://github.com/divio/django-filer/pull/916
thanks anyways!

**Comment by tdsymonds** [comment]
Ah ok thanks @vxsx for letting me know.

**Comment by yakky** [comment]
@vxsx  @tdsymonds so we can close this, right?

**Comment by vxsx** [comment]
aye

**Pull request closed without merging**
