### PR TITLE
Add download button to column actions in directory listings

### PR DESCRIPTION
**Pull request by k8n**
Too many clicks to download an actual file otherwise.

### CODE REVIEW

**Comment by yakky** [comment]
@czpython @FinalAngel @vxsx ? I'd say it's not without merit, even if filer folder listing it's not for downloading files

**Comment by vxsx** [comment]
i'm okay with that

**Comment by czpython** [comment]
👍

**Comment by FinalAngel** [comment]
👍  please also mention this in the changelog

**Comment by yakky** [comment]
@k8n could add the changelog item to this PR?

After that it's good to merge
Thanks

**Comment by k8n** [comment]
Oy. Did I completely mess up this PR by rebasing to the parent branch and then updating the CHANGELOG.txt?

**Comment by yakky** [comment]
yeah, it's more a github glitch than your fault. The only option, though, is to reopen a new Pr

**Comment by czpython** [comment]
I think the problem is the develop branch has commits not in master, I recommend creating a new PR targeting the develop branch instead of master.

@yakky 
We should get rid of that develop or master branch at some point.

**Pull request closed without merging**
