### PR TITLE
Fix #1035 -- Hide 'Save as new' button

### LINKED ISSUE #1035: hide "Save as New" button
A click on "Save as New" will raise into PermissionDenied, because filer.admin.permissions.PrimitivePermissionAwareModelAdmin.has_add_permission() will always return False, see: https://github.com/divio/django-filer/blob/develop/filer/admin/permissions.py#L9

So, the "Save as New" button should not be exists...

### PR DESCRIPTION
**Pull request by joncasdam**
Remove the hack (as defined by the code comment) so the button is not
visible anymore.

Also, it seems to me that the 'hack' is not needed anymore - if it's still needed, this PR might introduce breaking changes.

### CODE REVIEW

**Comment by yakky** [comment]
@joncasdam would you add a line in the changelog? I already opened the 1.3.3 section

**Comment by joncasdam** [comment]
Sure! On it.

**Comment by joncasdam** [comment]
Done: amended.

**Comment by yakky** [comment]
@joncasdam thanks for your contribution!

**Pull request merged**
