### PR TITLE
Test for missing migrations

### PR DESCRIPTION
**Pull request by Chronial**
This adds a test to the test-suite that checks for missing migrations.

As expected (#877), it is currently failing.

### CODE REVIEW

**Comment by yakky** [comment]
@Chronial would you add the missing migration to this PR?

**Comment by Chronial** [comment]
How do you generate migrations?

**Comment by yakky** [comment]
@Chronial if you ran the tests with tox, enter any django 1.8 virtualenv (eg: `` source ~/.toxenvs/django-filer/py35-dj18-custom_image-thumbs2x/bin/activate``) and run ``python test_settings.py makemigrations`` from the repository root

**Comment by Chronial** [comment]
Thx, added the missing migrations. Build should pass now, but it looks like travis doesn't like building at the moment.

**Comment by yakky** [comment]
@Chronial apparently a test application needs a further migration use ``python test_settings.py makemigrations extended_app`` to generate it

**Comment by yakky** [comment]
@Chronial great!

**Comment by Chronial** [comment]
Now I'm waiting for my release ;)

**Comment by yakky** [comment]
@Chronial getting things into shape for it!

**Comment by yakky** [comment]
@Chronial here we go!

**Pull request merged**
