### PR TITLE
adds missing @2x icons

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

https://github.com/divio/django-filer/issues/410

- adds missing @2x icons
- updates old icons with new design

### CODE REVIEW

**Comment by Brankub** [comment]
can't find  filer/static/filer/icons/plainfolder.png

**Comment by Brankub** [comment]
and plainfolder_32x32.png

**Comment by lory87** [comment]
@Brankub I just added the icons in every size from 512x512 to 16x16 and x2.

**Comment by Brankub** [comment]
👍

**Pull request merged**
