### PR TITLE
Generate thumbnails management command

### PR DESCRIPTION
**Pull request by jakob-o**

### CODE REVIEW

**Comment by jakob-o** [comment]
If you wonder why I don't iterate over the queryset itself: I tested this command with ~1.7k images with an average of 10MB per image and this was the only way to keep memory consumption stable and not rocketing through the roof...

**Comment by mkoistinen** [comment]
LGTM, thank you!

**Comment by jakob-o** [comment]
@mkoistinen Hey, please have a look if you are happy with the wording and everything. Let me know if you need anything changed.

**Comment by yakky** [comment]
LGTM

**Comment by vstoykov** [comment]
@jakob-o you can rebase your branch because there are some conflicts

**Pull request closed without merging**
