### PR TITLE
Django 2 support - continuation of #1030

### PR DESCRIPTION
**Pull request by wooyek**
I don't know how to improve an existing #1030 so I created a new PR.

### CODE REVIEW

**Comment by mixtah** [comment]
Any release plans for this soon?

**Comment by webus** [comment]
@wooyek pls, look at https://github.com/wooyek/django-filer/blob/feature/django2-support/filer/admin/imageadmin.py#L5

`from django.utils.translation import string_concat`
`string_concat` deprecated since Django version 1.11

**Comment by wooyek** [comment]
I am currently on vacation. Can we make compatibility with django 2.1 an another issue? In current pace and trying to make it all in one PR we'll soon have to workout 2.2 compatibility issues here and never getting a filer release out the door.

Please feel free to make another PR with broader compatibility and trash this PR.

**Comment by admed** [comment]
When it will be merged?

**Comment by peterfarrell** [comment]
When will this be merged?

**Comment by wooyek** [comment]
Closing in favor o #1096

**Pull request closed without merging**
