### PR TITLE
Add Django 1.10 migration

### LINKED ISSUE #920: Need to add migrations to go with Django 1.10 changes

### PR DESCRIPTION
**Pull request by yakky**
Fix #920

### CODE REVIEW

**Comment by yakky** [comment]
@czpython are you ok with this hackish solution? This is generated automatically from Django 1.10 but it's not compatible with 1.9 and below. So just ignoring it's the only viable solution to me

**Comment by czpython** [comment]
@yakky What happens if this runs on versions < 1.10? Altermodeloption has been around since 1.7

**Comment by yakky** [comment]
Altermodeloption is not the issue, but rather the ``'default_manager_name'``  which has been introduced in Django 1.10.
In Django 1.9 and below the migration is simply ignored. Intstruction does not alter in any way the database schema, and thus it's safe to ignore on Django versions which does not support it

**Comment by czpython** [comment]
@yakky ok to merge but please add a comment on the condition as to why we're doing this.

**Comment by yakky** [comment]
@czpython done. Will merge at the end of the test run

**Comment by jschneier** [comment]
Yep I was going to do the same thing.

**Comment by jschneier** [comment]
Oh the one thing I'll note is that maybe we shouldn't have a hard dependency on:
 
`from filer.utils.compatibility import GTE_DJANGO_1_10`

We won't be able to remove that in the future then (say when Django 2.0) or whatever comes out and we don't support Django < 1.10.

**Comment by yakky** [comment]
Why shouldn't be able to remove the import?

**Comment by jschneier** [comment]
We could. I'm worried about an unlikely situation, maybe impossible (we remove the compat helper but forget to remove it from here and that breaks the app for everyone). I guess we'll want to remove the if check regardless so it's fine.

**Comment by yakky** [comment]
tests runs with migration activated, thus if we remove the compat helper the tests will fail
In case we will remove 1.9 support, we can just remove the check and let migration run in any case

**Pull request merged**
