### PR TITLE
Fixes search field overflow #956

### PR DESCRIPTION
**Pull request by ArtistsTechGuy**
Removes minimum visible characters in search field.

### CODE REVIEW

**Comment by deeaarbee** [comment]
Please merge this fix!

**Comment by raeuz** [comment]
+1

**Comment by lam015** [comment]
This will help a lot.
Please merge.

**Comment by YegorDB** [comment]
+1

**Comment by wfehr** [comment]
bump!

**Comment by FinalAngel** [comment]
Thanks for the contribution @ArtistsTechGuy

**Pull request merged**
