### PR TITLE
Missing icons in 'static()' calls

### PR DESCRIPTION
**Pull request by mikek**
Add missing icons and use safer `static()` calls in IconsMixin.

See code comments and #438 for details.

- [x] IconsMIxin: workaround for static() call on possibly non-existent file
- [x] Add test cases for missing files in `static()` calls
- [x] Revert "remove 16x16px icon size
- [x] Add all missing icons in `static/filer/icons` for sizes of 16/32/48/64px

### CODE REVIEW

**Comment by mikek** [comment]
@lory87, please add missing icons. Feel free to ping me if you need any further info.

**Comment by cyberstar** [comment]
LGTM

**Comment by intellectronica** [comment]
:+1:

**Comment by vxsx** [comment]
FE :+1:

**Pull request merged**
