### PR TITLE
Add Django 2.0 support

### LINKED ISSUE #1026: it is compatible with django 2.0?
If not, whats upgrade forecast to be?

### PR DESCRIPTION
**Pull request by yakky**
Includes #1022

Fix #1022 
Fix #1026 
 

OSX builds are failing because some tools cannot be found, but this does not look related to the current PR

### CODE REVIEW

**Comment by POD666** [comment]
When this is going to be merged and released?

**Comment by jrief** [comment]
Before releasing a new version please also consider to merge #912.
All change requests from @czpython have been integrated.
Failing unit tests are not caused by this PR, but rather by a weird bug in the setup of tox in **django-filer**.

**Comment by gvizquel** [comment]
pip install -U Django
django-filer 1.3.2 has requirement Django<1.11.999,>=1.8, but you'll have django 2.0.4 which is incompatible.

¿How can I help?

**Comment by yakky** [comment]
@gvizquel fixed thanks!

**Pull request closed without merging**
