### PR TITLE
Fix swappable image

### PR DESCRIPTION
**Pull request by stefanfoulis**
Squashed version of #857 with updated testsuite.

### CODE REVIEW

**Comment by stefanfoulis** [comment]
@skirsdeda I'm still getting the error with ``Django>=1.10``.

**Comment by skirsdeda** [comment]
@stefanfoulis It seems that I'll have to fix django-polymorphic because it tries to validate model manager on polymorphic models (only excluding abstract models) whereas manager on a swapped model is inaccessible as well. So this might be a bit of a setback unless we can work out some workaround.

**Comment by skirsdeda** [comment]
@stefanfoulis I did the tests and confirmed that the problem is in django-polymorphic. See django-polymorphic/django-polymorphic#307 which fixes the issue.

**Comment by stefanfoulis** [comment]
@skirsdeda cool! 
Since this PR works for non swappable models anyway and is already an great improvement in its current state, I'd say we should merge it already now.
Then when django-polymorphic is released with that fix, we can just update the test-suite to require passing tests for ``Django>=1.10`` with swappable models.

**Comment by skirsdeda** [comment]
@stefanfoulis agreed 👍

**Comment by stefanfoulis** [comment]
Hmmm....I wonder why we're limiting to ``django-polymorphic<1.1`` in ``setup.py`` (https://github.com/divio/django-filer/blob/60c15fe9728c6b40a0b8cfdcb8a4b9a6f0ed3fb1/setup.py#L32)

**Comment by skirsdeda** [comment]
My guess is that this limit is completely artificial because it was just raised from another version to what was the newest version of django-polymorphic at that time.

**Pull request merged**
