### PR TITLE
Multiple FilerField inside an admin Inline doesn't work

### PR DESCRIPTION
**Pull request by acatton**
This fixes multiple issues:

  * Having multiple filerfield on one page
  * Having filerfield inside an admin inline

This fixes depends on some fixes made by #670.

### CODE REVIEW

**Comment by acatton** [comment]
@Flight, this is re-factoring the whole JavaScript and HTML and I see that you keep changing this file on master. I was just wondering if it was worth reviewing that before making any change on the `develop` branch?

Thanks.

**Comment by acatton** [comment]
@gavinwahl or @julianandrews might takeover. To have a better diff with develop, use `git diff -b upstream/develop` to ignore white spaces change (because of re-indentation)

**Comment by mkoistinen** [comment]
@acatton This is also good stuff, but what is the status of this PR?

**Comment by acatton** [comment]
Thanks for the review @mkoistinen, @julianandrews or @gavinwahl are supposed to take over this pull request.

**Comment by julianandrews** [comment]
@mkoistinen I think rebasing these changes is going to be more work than redoing them, especially since @acatton can't work on this anymore. I'm going to take over #670 and try to add what I can of these changes over top rather than trying to fix this pull request.

**Comment by stefanfoulis** [comment]
Do I understand correctly, that this PR can be closed in favour of #670?

**Comment by julianandrews** [comment]
@stefanfoulis Yup, this commit can definitely be closed.

I'm working on rebasing the other PR now, and it should include most of the changes from here.

**Comment by stefanfoulis** [comment]
:yum: awesome

**Pull request closed without merging**
